In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
X = pd.DataFrame()
X['X1'] = np.arange(10)
X['X2'] = ['a'] * 10
X.loc[3,'X2'] = 'b'
X['X3'] = X['X1'] * X['X2']
X

X1 X2         X3
0   0  a           
1   1  a          a
2   2  a         aa
3   3  b        bbb
4   4  a       aaaa
5   5  a      aaaaa
6   6  a     aaaaaa
7   7  a    aaaaaaa
8   8  a   aaaaaaaa
9   9  a  aaaaaaaaa

# numeric_column

In [3]:
def scale(x):
    mean = 5.
    std = 1.5
    return (tf.cast(x,dtype=tf.float32) - mean) / std

feature_columns = [
    tf.feature_column.numeric_column('X1', normalizer_fn=scale),
    tf.feature_column.indicator_column(
        tf.feature_column.categorical_column_with_vocabulary_list('X2', vocabulary_list=['a','b'])
    )
]

features = {
    'X1': tf.convert_to_tensor(X['X1']),
    'X2': tf.convert_to_tensor(X['X2'])
}

net = tf.feature_column.input_layer(features, feature_columns)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    sess.run(tf.tables_initializer())
    
    result = sess.run(net)
result

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
The old _

array([[-3.3333333,  1.       ,  0.       ],
       [-2.6666667,  1.       ,  0.       ],
       [-2.       ,  1.       ,  0.       ],
       [-1.3333334,  0.       ,  1.       ],
       [-0.6666667,  1.       ,  0.       ],
       [ 0.       ,  1.       ,  0.       ],
       [ 0.6666667,  1.       ,  0.       ],
       [ 1.3333334,  1.       ,  0.       ],
       [ 2.       ,  1.       ,  0.       ],
       [ 2.6666667,  1.       ,  0.       ]], dtype=float32)

# Bucketized column

In [4]:
numeric_feature_column = tf.feature_column.numeric_column('X1')

bucketized_feature_column = tf.feature_column.bucketized_column(
    source_column = numeric_feature_column,
    boundaries = [3, 5, 8]
)

feature_columns = [
    bucketized_feature_column,
    #tf.feature_column.numeric_column('X2')
    tf.feature_column.indicator_column(
        tf.feature_column.categorical_column_with_vocabulary_list('X2', vocabulary_list=['a','b'])
    )
]

features = {'X1':X['X1'], 'X2':X['X2']}

net = tf.feature_column.input_layer(features, feature_columns)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    sess.run(tf.tables_initializer())
    
    result = sess.run(net)
result

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.


array([[1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1., 0.]], dtype=float32)

# categorical_column_with_identity - One hot

In [5]:
categorical_column = tf.feature_column.categorical_column_with_identity('X1', num_buckets=15)
indicator_column = tf.feature_column.indicator_column(categorical_column)

feature_columns = [
    indicator_column,
]

features = {'X1':X['X1'], 'X2':X['X2']}

net = tf.feature_column.input_layer(features, feature_columns)

with tf.Session() as sess:
    result = sess.run(net)
result

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]],
      dtype=float32)

# categorical_column_with_hash_bucket

In [6]:
categorical_column = tf.feature_column.categorical_column_with_hash_bucket(key='X3', hash_bucket_size=10)
indicator_column = tf.feature_column.indicator_column(categorical_column)

feature_columns = [
    indicator_column
]

features = {'X1':X['X1'], 'X2':X['X2'], 'X3':X['X3']}

net = tf.feature_column.input_layer(features, feature_columns)

with tf.Session() as sess:

    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())

    result = sess.run(net)
result

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

# Crossed column

In [7]:
product = tf.feature_column.categorical_column_with_vocabulary_list(
    'X2', vocabulary_list=X['X2'].unique())
#product = tf.feature_column.indicator_column(product)

customer = tf.feature_column.categorical_column_with_identity(
    'X1', num_buckets=10)
#customer = tf.feature_column.indicator_column(customer)

crossed = tf.feature_column.crossed_column([product, customer], hash_bucket_size=10)

crossed = tf.feature_column.indicator_column(crossed)

feature_columns = [crossed]

features = {'X1':X['X1'], 'X2':X['X2']}

net = tf.feature_column.input_layer(features, feature_columns)

with tf.Session() as sess:

    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())
    
    result = sess.run(net)
result

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.


array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)